x86: Remove __strstr_generic prototype
This is not really require and clang throws a attribute declaration must
precede definition:

  ../sysdeps/x86_64/multiarch/strstr.c:37:54: error: attribute declaration
  must precede definition [-Werror,-Wignored-attributes]
  extern __typeof (__redirect_strstr) __strstr_generic attribute_hidden;
                                                       ^
  ./../include/libc-symbols.h:423:43: note: expanded from macro
  'attribute_hidden'
  # define attribute_hidden __attribute__ ((visibility ("hidden")))
                                            ^
  ../string/strstr.c:76:1: note: previous definition is here
  STRSTR (const char *haystack, const char *needle)
  ^
  ../sysdeps/x86_64/multiarch/strstr.c:27:16: note: expanded from macro
  'STRSTR'
  #define STRSTR __strstr_generic
                 ^
  1 error generated.